name: Self-Hosted Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build Backend Docker Image
      - name: Build backend Docker image
        run: |
          cd backend
          docker build -t tutorial:v1 .

      # Stop & Remove Old Backend Container
      - name: Restart backend container
        run: |
          docker run -d -p 3000:3000 --name Backend tutorial:v1

      # Build Frontend Docker Image
      - name: Build frontend Docker image
        run: |
          cd frontend
          docker build -t frontend:v1 .

      # Stop & Remove Old Frontend Container
      - name: Restart frontend container
        run: |
          docker run -d -p 4200:80 --name Tutorials frontend:v1
